// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js 把密钥放在 .env.local；Prisma CLI 默认只读 .env，这里显式加载 .env.local。
config({ path: ".env.local" });
config(); // 兜底：若存在 .env 也加载（不覆盖已存在的变量）

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate/CLI 用直连串（非 pooler），Prisma 7 已移除 directUrl
    url: process.env["DIRECT_URL"],
  },
});
